summary: |
    Single yum transaction validation

description: |
    Verify that we are doing a proper rollback during the validation phase in
    our transactions.
    If any errors occurs during the transaction resolution, either by
    downloading a package, dependency resolver and etc., the rollback should
    start and revert the changes to the system.
    We simulate the error by removing the entitlement certs found at /etc/pki/entitlement
    at a specific times during the transaction validation.

link: https://issues.redhat.com/browse/RHELC-576

tier: 0

tag+:
    - transaction


/transaction_validation_error:
    summary+: |
        Error during processing the transaction
    description+: |
        This test case removes the certs during the transaction processing
        to throw the following yum error: pkgmanager.Errors.YumDownloadError
    adjust+:
        - enabled: false
          when: distro == centos-8, alma-8, rocky-8, oracle-8
    tag+:
        - transaction-validation-error
    test: |
        pytest -svv -m test_transaction_validation_error


/package_download_error:
    summary+: |
        Error during the package download
    description+: |
        This test case removes the certs during the package download phase for both yum and dnf transactions.
    tag+:
        - package-download-error
    test: |
        pytest -svv -m test_package_download_error


/validating_packages_with_in_name_period:
    enabled: false
    adjust+:
        - enabled: true
          when: >
            distro == oracle-8, centos-8
    summary+: |
        Unhandled exception for packages with in name period
    description+: |
        This test verifies that packages with period in their name are parsed correctly.
        1/ Install problematic packages with period in name using packages_with_period fixture.
            E.g. python3.11-3.11.2-2.el8.x86_64 java-1.8.0-openjdk-headless-1.8.0.372.b07-4.el8.x86_64
        2/ Run conversion and expect no issues with the transaction validation.
            If there are issues with the Unhandled exception was caught: too many values to unpack (expected 2),
            raise AssertionError.
        3/ End the conversion at the Point of no return
    tag+:
        - validation-packages-with-in-name-period
        - sanity
    test: |
        pytest -svv -m test_validation_packages_with_in_name_period
